# Generated by Django 5.1.1 on 2024-10-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
